name: OrbitDB Test

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
      input_cid:
        type: string
        description: 'Optional CID to retrieve using ipfs get'
        required: false
        default: ''
  # TODO: run every 6 hours
  # schedule:
  # - cron: '0 */6 * * *'

# TODO:
# env:
#   ORBITDB_ADDRESS: /orbitdb/zdpuAtC9rFwpYrjeoZF6oqdhMmDT6sooqWxYBqiZ3iZdbqfRN

jobs:
  setup-ipfs:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # TODO: Add macOS and Windows
          # - macos-latest
          # - windows-latest
        ipfs:
          - ^0.34.1
    runs-on: ${{ matrix.os }}
    name: Setup IPFS on ${{ matrix.os }} with IPFS ${{ matrix.ipfs }}
    steps:
    - name: Set up IPFS ${{ matrix.ipfs }}
      # https://github.com/ibnesayeed/setup-ipfs/commits/c779340c110024feeb46579fef211c89332caf85
      uses: ibnesayeed/setup-ipfs@c779340c110024feeb46579fef211c89332caf85
      id: ipfs_setup
      with:
        ipfs_version: ${{ matrix.ipfs }}
        run_daemon: true
    - name: Test IPFS ${{ steps.ipfs_setup.outputs.resolved_ipfs_version }} CLI and API
      shell: bash
      run: |
        set -o pipefail
        # FIXME: Error: invalid path "/readme": path does not have enough components
        # ipfs cat ${{ steps.ipfs_setup.outputs.welcome_ref }}/readme
        curl -sX POST http://localhost:5001/api/v0/version | jq -e .
        curl -sX POST http://localhost:5001/api/v0/version | jq -e '(.Version=="${{ steps.ipfs_setup.outputs.resolved_ipfs_version }}")'

    - name: Get input CID with 'ipfs get' (if provided)
      # Only run if triggered manually AND the input_cid is not empty
      if: github.event_name == 'workflow_dispatch' && inputs.input_cid != ''
      shell: bash
      run: |
        echo "Attempting to get CID: ${{ inputs.input_cid }}"
        ipfs get ${{ inputs.input_cid }}
        echo "Successfully retrieved CID: ${{ inputs.input_cid }}"

    # Enable tmate debugging of manually-triggered workflows if the input option was provided
    - name: Setup tmate session
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      # https://github.com/mxschmitt/action-tmate/releases/tag/v3.19
      uses: mxschmitt/action-tmate@e5c7151931ca95bad1c6f4190c730ecf8c7dde48
      with:
        timeout-minutes: 60
    - name: Wait for IPFS daemon
      if: ${{ inputs.debug_enabled != true }}
      run: sleep 3600
      shell: bash

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 'lts/*'
  #     - run: npm ci

  #     # - name: Cache OrbitDB data
  #     #   uses: actions/cache/restore@v4
  #     #   id: orbitdb-cache
  #     #   with:
  #     #     path: |
  #     #       ./data/ipfs-composed-test
  #     #       ./data/orbitdb-composed
  #     #     key: orbitdb-data-cache

  #     - name: Run test
  #       run: node src/composed-storage-test.js

  #     # - name: Save OrbitDB data (always)
  #     #   if: always()
  #     #   uses: actions/cache/save@v4
  #     #   with:
  #     #     path: |
  #     #       ./data/ipfs-composed-test
  #     #       ./data/orbitdb-composed
  #     #     key: orbitdb-data-cache
